[package]
name = "urnik-demoralizer"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = { version = "0.6", default-features = false, features = ["track-caller"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ureq = "2.7"
